// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLEnzWFHpYcdn_revGKphQu6wca4M5JSw',
    appId: '1:994500099648:web:7e3047ec6839e57106a9a5',
    messagingSenderId: '994500099648',
    projectId: 'daycare-push',
    authDomain: 'daycare-push.firebaseapp.com',
    storageBucket: 'daycare-push.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNsRb4pEryBkUI1BZBGRFSF3Xk9EyUYd4',
    appId: '1:994500099648:android:8bd3eb544910493b06a9a5',
    messagingSenderId: '994500099648',
    projectId: 'daycare-push',
    storageBucket: 'daycare-push.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUJOnTplKI7fWpTHX74JrbzOh3lXRYlDI',
    appId: '1:994500099648:ios:ae779d220096713006a9a5',
    messagingSenderId: '994500099648',
    projectId: 'daycare-push',
    storageBucket: 'daycare-push.appspot.com',
    iosClientId: '994500099648-e0906ve39mfd68g8f5n4p8lk33ntca2o.apps.googleusercontent.com',
    iosBundleId: 'com.example.daycareMgmtFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUJOnTplKI7fWpTHX74JrbzOh3lXRYlDI',
    appId: '1:994500099648:ios:ae779d220096713006a9a5',
    messagingSenderId: '994500099648',
    projectId: 'daycare-push',
    storageBucket: 'daycare-push.appspot.com',
    iosClientId: '994500099648-e0906ve39mfd68g8f5n4p8lk33ntca2o.apps.googleusercontent.com',
    iosBundleId: 'com.example.daycareMgmtFrontend',
  );
}
